import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import { NavigationProvider } from "./context/ActiveItemContext";



export const metadata: Metadata = {
  title: "Yudo-Gram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className="antialiased">
        
        <NavigationProvider defaultActiveItem="dashboard">
        <Navbar  />
          {children}
        </NavigationProvider>
        
      </body>
    </html>
  );
}