import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Nav";
import Sidebar from "@/components/SideBar"

export const metadata: Metadata = {
  title: "Yudo-Gram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className="antialiased">
        {/* <Navbar /> */}
     
        {children}
      </body>
    </html>
  );
}